language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
install:
  - npm install -g yarn
  - yarn generate-lock-entry
  - yarn install
  - yarn check --integrity
cache:
  yarn: true
  directories:
    - node_modules
