language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
install:
  - npm install -g yarn
  - yarn install --pure-lockfile
  - yarn check --integrity
before_install:
  - 'npm i -g npm@latest'
cache: yarn
  yarn: true
  directories:
    - node_modules
